import {
  Si1Password,
  SiAmazonwebservices,
  SiAngular,
  SiAntdesign,
  SiBun,
  SiCakephp,
  SiChartdotjs,
  SiCircleci,
  SiClickhouse,
  SiCloudflare,
  SiCmake,
  SiCocoapods,
  SiCoinbase,
  SiD3Dotjs,
  SiDatadog,
  SiDeno,
  SiDiscord,
  SiDocker,
  SiDrizzle,
  SiErlang,
  SiFacebook,
  SiFramer,
  SiGit,
  SiGithub,
  SiGooglecloud,
  SiGrafana,
  SiHono,
  SiI18Next,
  SiInstagram,
  SiJenkins,
  SiKubernetes,
  SiLemonsqueezy,
  SiLinkedin,
  SiLua,
  SiMobx,
  SiMongodb,
  SiMongoose,
  SiMui,
  SiMysql,
  SiNeo4J,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiNvm,
  SiOpenai,
  SiOpenjdk,
  SiOpenssl,
  SiOpsgenie,
  SiPm2,
  SiPostcss,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPuppeteer,
  SiPython,
  SiRadixui,
  SiReact,
  SiRealm,
  SiRecoil,
  SiRedis,
  SiRedux,
  SiRefine,
  SiResend,
  SiRevolut,
  SiRuby,
  SiRust,
  SiSass,
  SiScala,
  SiScipy,
  SiSentry,
  SiServerless,
  SiSharp,
  SiSnowflake,
  SiSpacy,
  SiSpotify,
  SiSpring,
  SiSqlalchemy,
  SiSqlite,
  SiStencil,
  SiStripe,
  SiSupabase,
  SiSvelte,
  SiSwagger,
  SiSwift,
  SiSymfony,
  SiSymphony,
  SiSympy,
  SiTailscale,
  SiTailwindcss,
  SiTensorflow,
  SiThreads,
  SiTsnode,
  SiTurborepo,
  SiTypeform,
  SiTypescript,
  SiUnsplash,
  SiVenmo,
  SiVercel,
  SiVim,
  SiVite,
  SiVuedotjs,
  SiWebpack,
  SiWikidotjs,
  SiWikipedia,
  SiWix,
  SiWordpress,
  SiX,
  SiXcode,
  SiZapier,
  SiZod,
  SiCss3,
  SiZoho,
  SiHtml5,
  SiIos,
  SiAndroid,
  SiApple,
  SiGoogle,
  SiLinux,
  SiMacos,
  SiFirefox,
  SiJavascript,
  SiSafari,
  SiBluesky,
} from "react-icons/si"
import { cn } from "@/lib/utils"
export const AppIcons = {
  angular: SiAngular,
  antDesign: SiAntdesign,
  objectivec: SiApple,
  aws: SiAmazonwebservices,
  buildSystems: SiTurborepo,
  bun: SiBun,
  cakephp: SiCakephp,
  css: SiCss3,
  html: SiHtml5,
  chartjs: SiChartdotjs,
  circleci: SiCircleci,
  clickhouse: SiClickhouse,
  cloudflare: SiCloudflare,
  coinbase: SiCoinbase,
  d3: SiD3Dotjs,
  datadog: SiDatadog,
  deno: SiDeno,
  designSystems: SiRadixui,
  discord: SiDiscord,
  docker: SiDocker,
  drizzle: SiDrizzle,
  erlang: SiErlang,
  facebook: SiFacebook,
  framer: SiFramer,
  gcp: SiGooglecloud,
  git: SiGit,
  github: SiGithub,
  grafana: SiGrafana,
  hono: SiHono,
  i18next: SiI18Next,
  instagram: SiInstagram,
  jenkins: SiJenkins,
  kubernetes: SiKubernetes,
  lemonsqueezy: SiLemonsqueezy,
  linkedin: SiLinkedin,
  lua: SiLua,
  makefile: SiCmake,
  mobx: SiMobx,
  mongo: SiMongodb,
  mongodb: SiMongodb,
  mongoose: SiMongoose,
  mui: SiMui,
  mysql: SiMysql,
  neo4j: SiNeo4J,
  nestjs: SiNestjs,
  next: SiNextdotjs,
  nextjs: SiNextdotjs,
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  numpy: SiNumpy,
  nvm: SiNvm,
  onepassword: Si1Password,
  openai: SiOpenai,
  openjdk: SiOpenjdk,
  openssl: SiOpenssl,
  opsgenie: SiOpsgenie,
  pm2: SiPm2,
  podfile: SiCocoapods,
  postcss: SiPostcss,
  postgresql: SiPostgresql,
  postman: SiPostman,
  prisma: SiPrisma,
  puppeteer: SiPuppeteer,
  python: SiPython,
  radixui: SiRadixui,
  react: SiReact,
  realm: SiRealm,
  recoil: SiRecoil,
  redis: SiRedis,
  redux: SiRedux,
  refine: SiRefine,
  resend: SiResend,
  revolut: SiRevolut,
  ruby: SiRuby,
  rust: SiRust,
  sass: SiSass,
  scala: SiScala,
  scipy: SiScipy,
  sentry: SiSentry,
  serverless: SiServerless,
  sharp: SiSharp,
  snowflake: SiSnowflake,
  spacy: SiSpacy,
  spotify: SiSpotify,
  spring: SiSpring,
  sqlalchemy: SiSqlalchemy,
  sqlite: SiSqlite,
  stencil: SiStencil,
  stripe: SiStripe,
  supabase: SiSupabase,
  svelte: SiSvelte,
  swagger: SiSwagger,
  swift: SiSwift,
  javascript: SiJavascript,
  symfony: SiSymfony,
  symphony: SiSymphony,
  sympy: SiSympy,
  tailscale: SiTailscale,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  tensorflow: SiTensorflow,
  threads: SiThreads,
  tsnode: SiTsnode,
  turborepo: SiTurborepo,
  twitter: SiX,
  typeform: SiTypeform,
  typescript: SiTypescript,
  unsplash: SiUnsplash,
  venmo: SiVenmo,
  vercel: SiVercel,
  vim: SiVim,
  vite: SiVite,
  vue: SiVuedotjs,
  webpack: SiWebpack,
  wikidotjs: SiWikidotjs,
  wikipedia: SiWikipedia,
  wix: SiWix,
  wordpress: SiWordpress,
  xcode: SiXcode,
  zapier: SiZapier,
  zod: SiZod,
  zoho: SiZoho,
  ios: SiIos,
  android: SiAndroid,
  apple: SiApple,
  google: SiGoogle,
  linux: SiLinux,
  macos: SiMacos,
  firefox: SiFirefox,
  bluesky: SiBluesky,
  safari: SiSafari,
}

export const Icon = ({
  name,
  color,
  className,
  size = 18,
}: {
  name: keyof typeof AppIcons
  color?: string
  className?: string
  size?: number
}) => {
  const IconComponent = AppIcons[name]
  if (!IconComponent) return null

  return <IconComponent className={cn(color, className)} size={size} />
}

export default Icon
