import {
  SiPrisma,
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiReact,
  SiRadixui,
  SiZod,
  SiAngular,
  SiSass,
  SiSvelte,
  SiVite,
  SiVuedotjs,
  SiPostgresql,
  SiMysql,
  SiNestjs,
  SiMongodb,
  SiMui,
  SiAntdesign,
  SiOpenai,
  SiPython,
  SiChartdotjs,
  SiTurborepo,
  Si1Password,
  SiAmazonwebservices,
  SiGooglecloud,
  SiCocoapods,
  SiCmake,
  SiSupabase,
  SiServerless,
  SiNodedotjs,
  SiDocker,
  SiKubernetes,
  SiJenkins,
  SiGit,
  SiGithub,
  SiStripe,
  SiSentry,
  SiLemonsqueezy,
  SiVercel,
  SiPostman,
  SiNumpy,
  SiScipy,
  SiPuppeteer,
  SiDrizzle,
  SiInstagram,
  SiX,
  SiFacebook,
  SiLinkedin,
} from "react-icons/si"
import { cn } from "@/lib/utils"
export const AppIcons = {
  prisma: SiPrisma,
  typescript: SiTypescript,
  next: SiNextdotjs,
  tailwind: SiTailwindcss,
  react: SiReact,
  radixui: SiRadixui,
  zod: SiZod,
  angular: SiAngular,
  sass: SiSass,
  svelte: SiSvelte,
  vite: SiVite,
  vue: SiVuedotjs,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  mui: SiMui,
  antDesign: SiAntdesign,
  openai: SiOpenai,
  nestjs: SiNestjs,
  python: SiPython,
  chartjs: SiChartdotjs,
  turborepo: SiTurborepo,
  onepassword: Si1Password,
  aws: SiAmazonwebservices,
  gcp: SiGooglecloud,
  podfile: SiCocoapods,
  makefile: SiCmake,
  supabase: SiSupabase,
  tailwindcss: SiTailwindcss,
  designSystems: SiRadixui,
  serverless: SiServerless,
  buildSystems: SiTurborepo,
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  nextjs: SiNextdotjs,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  jenkins: SiJenkins,
  git: SiGit,
  github: SiGithub,
  stripe: SiStripe,
  sentry: SiSentry,
  lemonsqueezy: SiLemonsqueezy,
  vercel: SiVercel,
  postman: SiPostman,
  numpy: SiNumpy,
  scipy: SiScipy,
  puppeteer: SiPuppeteer,
  drizzle: SiDrizzle,
  instagram: SiInstagram,
  twitter: SiX,
  facebook: SiFacebook,
  linkedin: SiLinkedin,
}

const Icon = ({
  name,
  color,
  size = 18,
}: {
  name: keyof typeof AppIcons
  color?: string
  size?: number
}) => {
  const Icon = AppIcons[name]
  return <Icon className={cn(color)} size={size} />
}

export default Icon
